basedir: \Users\uptim\Documents\GitHub\topseed-dev\www
id: 28713ee7-c49f-476e-a395-50b5e74ec5ee

sourceUrl: http://awwwards.com/collections
title: Web Design Trends
media_url: aw.jpg
description: The awards for design, creativity and innovation on the Internet. Awwwards are the Website Awards that recognize and promote the talent and effort of the best developers, designers and web agencies in the world.
author: awwwards.com
updated: 1522597132

link: www.
